# Cloudflare Pages + D1 configuration.
name = "pkuml-mleague"
pages_build_output_dir = "dist"
compatibility_date = "2025-06-01"

[[d1_databases]]
binding = "DB"
database_name = "pkuml-d1"
database_id = "53f2c3f2-b957-4677-9cf9-8d3d40ecc2c1"
